### PR TITLE
checkPrices(), updateIndexer() & Footer

### LINKED ISSUE #4: Add a footer to the app
The app doesn't have a footer right now, let's reuse the one from the website maybe?

### LINKED ISSUE #16: Update the app when new events are happening
We need to update the app when new events are happening, I think a simple solution for now would be to query the indexer every x seconds.

### LINKED ISSUE #20: Improve Prices context to fetch specific price on demand
Instead of fetching a premade list of prices when the app is loaded, we should only get prices on demand.
For example we could add a `getPrice` function to the `PricesContext` that would check the state before returning the price: if the price is always there we simply return it, otherwise we trigger an API call.

### PR DESCRIPTION
**Pull request by zachdt**
Added a simple footer closes #4 

Need to determine the best state changes to check prices within the app, right now its only implemented when we check balances in create-pool but can be used anywhere, upon input for example.  

We dont perform nearly enough calls to warrant checking only specific prices in my opinion, but this function can be easily extended to do so.  Just need to change [check, setCheck] to a string in the useEffect() and pass it in the function.

Closes #20

IndexContext update function may be called where desired.

Closes #16

### CODE REVIEW

**Comment by clemlak** [comment]
Regarding the footer I think the disclaimer is a bit too large no? We can include it again in the wallets selection modal with a "Accept terms" maybe, but the footer font size can be reduced. Also we might want to center it or have the links below the disclaimer?

I have an idea based on what you did for the prices:
- We should prepare a list of all the tokens when we fetch the current pools, then we can use DexScreener to get all the prices in one batch and store then into the context
- Then similarly to what you did, we can just fetch a new price when someone is adding an "unknown token" to create a new pool for example

**Comment by zachdt** [comment]
@clemlak improved updatePrices, right now i think a single string input, called upon various references to _tokenX/Y.symbol, is the cleanest.  there is not obvious advantage to batch calling prices at our current dex screen api limit (high i assume).

**Comment by clemlak** [comment]
Can you just reduce the size of the disclaimer before we merge this branch?

**Comment by zachdt** [comment]
need this in before next.js migration, just need to pass review

**Review by kinrezC — APPROVED** [review]

**Pull request merged**
